/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-01-14 17:53:03 UTC)
 * on 2015-03-14 at 00:35:05 UTC 
 * Modify at your own risk.
 */

package com.pipoll.entity.pollendpoint.model;

/**
 * Model definition for Poll.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the pollendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Poll extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Category category;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String createDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long createdAt;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer downvotes;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String image;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String theme;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<TrendNews> trendNews;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String updateDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long updatedAt;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer upvotes;

  /**
   * @return value or {@code null} for none
   */
  public Category getCategory() {
    return category;
  }

  /**
   * @param category category or {@code null} for none
   */
  public Poll setCategory(Category category) {
    this.category = category;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCreateDate() {
    return createDate;
  }

  /**
   * @param createDate createDate or {@code null} for none
   */
  public Poll setCreateDate(java.lang.String createDate) {
    this.createDate = createDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getCreatedAt() {
    return createdAt;
  }

  /**
   * @param createdAt createdAt or {@code null} for none
   */
  public Poll setCreatedAt(java.lang.Long createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getDownvotes() {
    return downvotes;
  }

  /**
   * @param downvotes downvotes or {@code null} for none
   */
  public Poll setDownvotes(java.lang.Integer downvotes) {
    this.downvotes = downvotes;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Poll setId(java.lang.String id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getImage() {
    return image;
  }

  /**
   * @param image image or {@code null} for none
   */
  public Poll setImage(java.lang.String image) {
    this.image = image;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTheme() {
    return theme;
  }

  /**
   * @param theme theme or {@code null} for none
   */
  public Poll setTheme(java.lang.String theme) {
    this.theme = theme;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<TrendNews> getTrendNews() {
    return trendNews;
  }

  /**
   * @param trendNews trendNews or {@code null} for none
   */
  public Poll setTrendNews(java.util.List<TrendNews> trendNews) {
    this.trendNews = trendNews;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUpdateDate() {
    return updateDate;
  }

  /**
   * @param updateDate updateDate or {@code null} for none
   */
  public Poll setUpdateDate(java.lang.String updateDate) {
    this.updateDate = updateDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getUpdatedAt() {
    return updatedAt;
  }

  /**
   * @param updatedAt updatedAt or {@code null} for none
   */
  public Poll setUpdatedAt(java.lang.Long updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getUpvotes() {
    return upvotes;
  }

  /**
   * @param upvotes upvotes or {@code null} for none
   */
  public Poll setUpvotes(java.lang.Integer upvotes) {
    this.upvotes = upvotes;
    return this;
  }

  @Override
  public Poll set(String fieldName, Object value) {
    return (Poll) super.set(fieldName, value);
  }

  @Override
  public Poll clone() {
    return (Poll) super.clone();
  }

}
